#pragma once

#include "DriverBase.h"

typedef VOID(*PROCESSENUM_CALLBACK)(PEPROCESS);
typedef VOID(*THREADENUM_CALLBACK)(PETHREAD);
typedef VOID(*MODULEENUM_CALLBACK)(PLDR_DATA_TABLE_ENTRY);

ULONG EnumProcess(PROCESSENUM_CALLBACK pFun);
ULONG EnumThread(PEPROCESS Process, THREADENUM_CALLBACK pFun);
ULONG EnumMoudle(PEPROCESS Process, MODULEENUM_CALLBACK pFun);
void ZwKillProcess(HANDLE Pid);